### ISSUE TITLE
Allow Global Template params

### ISSUE THREAD

**Issue by rnpridgeon** [suborbital/sdk#13]
template.toml should allow you to set common parameters globally while allowing individual template specs to override their values. 

i.e. 

```toml
[templates]

api_version = "0.16.3"
lang = "tinygo"
main = "main.go"

[templates.EventNewShipment]
path = "event/receivables"

[templates.EventShipmentProcessed]
path = "event/processing"

[templates.EventShipmentDelivered]
path = "event/confirmations"
api_version = "0.16.5"

[templates.EventNotify]
path = "event/notifications
lang = "javascript"
main = "index.js"
```
